/**
 * Turn the folder of logo candidates into something a browser can open.
 *
 * The originals are 1254px PNGs, ~1.4 MB each, 85 MB for the set. A page
 * that puts sixty of those on screen is not a voting page, it is a
 * download. Each one becomes two WebPs — a tile for the grid and a
 * larger one for looking closely — and a manifest so the app knows what
 * exists without reading the filesystem at request time.
 *
 * Re-runnable. Point it at the folder again after adding a candidate and
 * it rebuilds everything, including the manifest.
 *
 * Run: npx tsx scripts/build-logo-options.ts [source-dir]
 */
import { mkdirSync, readdirSync, writeFileSync, rmSync } from "node:fs";
import { basename, extname, join } from "node:path";
import sharp from "sharp";

const SOURCE =
  process.argv[2] ??
  "/Users/ruilinyuan/Documents/Codex/2026-06-08/redesign-this-page-using-html-and/outputs/logos/biohubnet-2026-options";

const OUT = "public/symposium-2026/logo-options";
const MANIFEST = "src/lib/symposium/logo-options.ts";

/** Grid tile. Small enough that sixty of them is still a light page. */
const TILE = { width: 400, quality: 78 };
/** For looking closely. Retina-sharp at the size the viewer shows it. */
const FULL = { width: 1000, quality: 80 };

/** "05-electric-blue.png" → { id: "05", label: "Electric blue" } */
function describe(file: string) {
  const stem = basename(file, extname(file));
  const m = stem.match(/^(\d+)[-_](.+)$/);
  const id = m ? m[1] : stem;
  const words = (m ? m[2] : stem).replace(/[-_]+/g, " ").trim();
  return { id, slug: stem, label: words.charAt(0).toUpperCase() + words.slice(1) };
}

async function main() {
  const files = readdirSync(SOURCE)
    .filter((f) => /\.(png|jpe?g|webp)$/i.test(f))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  if (files.length === 0) throw new Error(`No images in ${SOURCE}`);

  // Rebuilt wholesale so a candidate removed from the folder does not
  // linger in public/ as a file nothing links to but everything ships.
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  const entries: { id: string; slug: string; label: string }[] = [];
  let bytes = 0;

  for (const f of files) {
    const d = describe(f);
    const src = join(SOURCE, f);
    for (const [suffix, cfg] of [["tile", TILE], ["full", FULL]] as const) {
      const buf = await sharp(src)
        .resize(cfg.width, cfg.width, { fit: "cover" })
        .webp({ quality: cfg.quality })
        .toBuffer();
      writeFileSync(join(OUT, `${d.slug}-${suffix}.webp`), buf);
      bytes += buf.length;
    }
    entries.push(d);
  }

  const manifest = `/**
 * The 2026 Symposium logo candidates.
 *
 * GENERATED by scripts/build-logo-options.ts — do not edit by hand.
 * Re-run that script after adding or removing a candidate.
 *
 * Ids are the number the file was given, and they are what a vote is
 * stored against. Renaming a file's DESCRIPTION is safe; renumbering it
 * would silently move everybody's votes to a different picture.
 */
export interface LogoOption {
  /** "05" — stable, and what a vote row points at. */
  id: string;
  /** "05-electric-blue" — the file stem. */
  slug: string;
  /** "Electric blue" — what a voter reads. */
  label: string;
}

export const LOGO_OPTIONS: LogoOption[] = ${JSON.stringify(entries, null, 2)};

/** How many candidates one person may pick. */
export const VOTES_PER_PERSON = 3;

export const tileSrc = (o: LogoOption) => \`/symposium-2026/logo-options/\${o.slug}-tile.webp\`;
export const fullSrc = (o: LogoOption) => \`/symposium-2026/logo-options/\${o.slug}-full.webp\`;

export const optionById = (id: string) => LOGO_OPTIONS.find((o) => o.id === id);
`;

  mkdirSync("src/lib/symposium", { recursive: true });
  writeFileSync(MANIFEST, manifest);

  console.log(`${files.length} candidates → ${OUT}`);
  console.log(`${(bytes / 1024 / 1024).toFixed(1)} MB total (was ~85 MB)`);
  console.log(`Manifest: ${MANIFEST}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
