/**
 * The 2026 Symposium logo candidates.
 *
 * GENERATED by scripts/build-logo-options.ts — do not edit by hand.
 * Re-run that script after adding or removing a candidate.
 *
 * Ids are the number the file was given, and they are what a vote is
 * stored against. Renaming a file's DESCRIPTION is safe; renumbering it
 * would silently move everybody's votes to a different picture.
 */
export interface LogoOption {
  /** "05" — stable, and what a vote row points at. */
  id: string;
  /** "05-electric-blue" — the file stem. */
  slug: string;
  /** "Electric blue" — what a voter reads. */
  label: string;
}

export const LOGO_OPTIONS: LogoOption[] = [
  {
    "id": "01",
    "slug": "01-emerald-cobalt",
    "label": "Emerald cobalt"
  },
  {
    "id": "02",
    "slug": "02-midnight-violet",
    "label": "Midnight violet"
  },
  {
    "id": "03",
    "slug": "03-slate-coral",
    "label": "Slate coral"
  },
  {
    "id": "04",
    "slug": "04-forest-lime",
    "label": "Forest lime"
  },
  {
    "id": "05",
    "slug": "05-electric-blue",
    "label": "Electric blue"
  },
  {
    "id": "06",
    "slug": "06-plum-magenta",
    "label": "Plum magenta"
  },
  {
    "id": "07",
    "slug": "07-monochrome-teal",
    "label": "Monochrome teal"
  },
  {
    "id": "08",
    "slug": "08-sand-ink-teal",
    "label": "Sand ink teal"
  },
  {
    "id": "09",
    "slug": "09-arctic-ice",
    "label": "Arctic ice"
  },
  {
    "id": "10",
    "slug": "10-dusk-turquoise",
    "label": "Dusk turquoise"
  },
  {
    "id": "11",
    "slug": "11-concentric-hub",
    "label": "Concentric hub"
  },
  {
    "id": "12",
    "slug": "12-diagonal-editorial",
    "label": "Diagonal editorial"
  },
  {
    "id": "13",
    "slug": "13-modular-grid",
    "label": "Modular grid"
  },
  {
    "id": "14",
    "slug": "14-numeral-windows",
    "label": "Numeral windows"
  },
  {
    "id": "15",
    "slug": "15-radial-hub",
    "label": "Radial hub"
  },
  {
    "id": "16",
    "slug": "16-pathway-ribbon",
    "label": "Pathway ribbon"
  },
  {
    "id": "17",
    "slug": "17-hexagonal-lattice",
    "label": "Hexagonal lattice"
  },
  {
    "id": "18",
    "slug": "18-asymmetrical-swiss",
    "label": "Asymmetrical swiss"
  },
  {
    "id": "19",
    "slug": "19-minimal-network-frame",
    "label": "Minimal network frame"
  },
  {
    "id": "20",
    "slug": "20-layered-portals",
    "label": "Layered portals"
  },
  {
    "id": "21",
    "slug": "21-brutalist-manifesto",
    "label": "Brutalist manifesto"
  },
  {
    "id": "22",
    "slug": "22-fragmented-numerals",
    "label": "Fragmented numerals"
  },
  {
    "id": "23",
    "slug": "23-vertical-spine",
    "label": "Vertical spine"
  },
  {
    "id": "24",
    "slug": "24-research-checkerboard",
    "label": "Research checkerboard"
  },
  {
    "id": "25",
    "slug": "25-negative-space-cross",
    "label": "Negative space cross"
  },
  {
    "id": "26",
    "slug": "26-double-helix-year",
    "label": "Double helix year"
  },
  {
    "id": "27",
    "slug": "27-neural-constellation",
    "label": "Neural constellation"
  },
  {
    "id": "28",
    "slug": "28-microscopy-cells",
    "label": "Microscopy cells"
  },
  {
    "id": "29",
    "slug": "29-genome-barcode",
    "label": "Genome barcode"
  },
  {
    "id": "30",
    "slug": "30-data-topography",
    "label": "Data topography"
  },
  {
    "id": "31",
    "slug": "31-bauhaus-geometry",
    "label": "Bauhaus geometry"
  },
  {
    "id": "32",
    "slug": "32-constructivist-diagonal",
    "label": "Constructivist diagonal"
  },
  {
    "id": "33",
    "slug": "33-art-deco-science",
    "label": "Art deco science"
  },
  {
    "id": "34",
    "slug": "34-international-grid",
    "label": "International grid"
  },
  {
    "id": "35",
    "slug": "35-mid-century-atom",
    "label": "Mid century atom"
  },
  {
    "id": "36",
    "slug": "36-layered-paper-cut",
    "label": "Layered paper cut"
  },
  {
    "id": "37",
    "slug": "37-translucent-glass-tiles",
    "label": "Translucent glass tiles"
  },
  {
    "id": "38",
    "slug": "38-folded-ribbon-sculpture",
    "label": "Folded ribbon sculpture"
  },
  {
    "id": "39",
    "slug": "39-isometric-research-city",
    "label": "Isometric research city"
  },
  {
    "id": "40",
    "slug": "40-spectral-hologram",
    "label": "Spectral hologram"
  },
  {
    "id": "41",
    "slug": "41-monospaced-terminal",
    "label": "Monospaced terminal"
  },
  {
    "id": "42",
    "slug": "42-serif-sans-editorial",
    "label": "Serif sans editorial"
  },
  {
    "id": "43",
    "slug": "43-kinetic-type-wave",
    "label": "Kinetic type wave"
  },
  {
    "id": "44",
    "slug": "44-monumental-cropped-digits",
    "label": "Monumental cropped digits"
  },
  {
    "id": "45",
    "slug": "45-dot-matrix-system",
    "label": "Dot matrix system"
  },
  {
    "id": "46",
    "slug": "46-mycelium-network",
    "label": "Mycelium network"
  },
  {
    "id": "47",
    "slug": "47-river-delta-systems",
    "label": "River delta systems"
  },
  {
    "id": "48",
    "slug": "48-coral-topology",
    "label": "Coral topology"
  },
  {
    "id": "49",
    "slug": "49-growth-rings",
    "label": "Growth rings"
  },
  {
    "id": "50",
    "slug": "50-leaf-vein-network",
    "label": "Leaf vein network"
  },
  {
    "id": "51",
    "slug": "51-bridge-spans",
    "label": "Bridge spans"
  },
  {
    "id": "52",
    "slug": "52-beacon-signal",
    "label": "Beacon signal"
  },
  {
    "id": "53",
    "slug": "53-open-knowledge-pages",
    "label": "Open knowledge pages"
  },
  {
    "id": "54",
    "slug": "54-compass-pathways",
    "label": "Compass pathways"
  },
  {
    "id": "55",
    "slug": "55-interlocking-tessellation",
    "label": "Interlocking tessellation"
  },
  {
    "id": "56",
    "slug": "56-orbital-vortex",
    "label": "Orbital vortex"
  },
  {
    "id": "57",
    "slug": "57-impossible-cube-network",
    "label": "Impossible cube network"
  },
  {
    "id": "58",
    "slug": "58-kinetic-stripe-interference",
    "label": "Kinetic stripe interference"
  },
  {
    "id": "59",
    "slug": "59-monochrome-couture",
    "label": "Monochrome couture"
  },
  {
    "id": "60",
    "slug": "60-celebratory-node-burst",
    "label": "Celebratory node burst"
  }
];

/** How many candidates one person may pick. */
export const VOTES_PER_PERSON = 3;

export const tileSrc = (o: LogoOption) => `/symposium-2026/logo-options/${o.slug}-tile.webp`;
export const fullSrc = (o: LogoOption) => `/symposium-2026/logo-options/${o.slug}-full.webp`;

export const optionById = (id: string) => LOGO_OPTIONS.find((o) => o.id === id);
